# Generated by Django 4.2.27 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text="The gloss/word for the sign (e.g., 'hello', 'thank_you')", max_length=100, unique=True)),
                ('sigml_file', models.FileField(help_text='Upload a .sigml file for this sign', upload_to='sigml/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
