# Generated by Django 4.2.27 on 2026-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign',
            options={'ordering': ['word']},
        ),
        migrations.AddField(
            model_name='sign',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sigml_file',
            field=models.FileField(upload_to='sigml/'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
